name: Create Discussion
on:
  push:
    branches: [rewrite]
    paths:
      - 'site/posts/**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      discussions: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get post metadata
        id: metadata
        run: |
          echo "::set-output name=title::$(grep -m 1 -oP '(?<=title: ).*' site/$GITHUB_HEAD_REF)"
          echo "::set-output name=filename::$(basename site/$GITHUB_HEAD_REF)"
          echo "::set-output name=slug::$(echo $GITHUB_HEAD_REF | sed 's/\.md//g')"
          

      - name: Build discussion
        id: build-discussion
        uses: nvdaes/build-discussion@v1
        with:
          repository: Kex1016/haiiro
          category-position: 1
          title: ${{ steps.metadata.outputs.title }}
          body: |
            ${{ steps.metadata.outputs.title }}
            ---
            [Read more](https://haiiro.moe/posts/${{ steps.metadata.outputs.slug }})

      - name: Print Output
        id: output
        run: |
          echo "${{ steps.build-discussion.outputs.discussion-id }}"
          echo "${{ steps.build-discussion.outputs.discussion-url }}"
          echo "${{ steps.build-discussion.outputs.discussion-number }}"